In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
cd E:미세먼지

E:\미세먼지

In [12]:
mise = pd.read_csv('mise0.csv',encoding = 'ms949')

In [13]:
date = mise['측정일시'].astype(str)
mise['연도'] = date.str.slice(start=0, stop=4).astype(str)
mise['월'] = date.str.slice(start=4, stop=6).astype(str)
mise['일'] = date.str.slice(start=6, stop=8).astype(str)
mise['시간'] = date.str.slice(start=8, stop=10).astype(str)

In [17]:
new = mise['지역'].str.split(' ', n = 1, expand = True) 
mise['시도'] = new[0]

In [14]:
mise.head()

,Unnamed: 0,CO,NO2,O3,PM10,PM25,SO2,망,주소,지역,측정소명,측정소코드,측정일시,연도,월,일,시간
0,0,0.6,0.015,0.023,47.0,38.0,0.004,NaN,강원 강릉시 옥천동,강원 강릉시,옥천동,632132,2016010101,2016,01,01,01
1,1,0.6,0.015,0.024,51.0,43.0,0.004,NaN,강원 강릉시 옥천동,강원 강릉시,옥천동,632132,2016010102,2016,01,01,02
2,2,0.6,0.014,0.024,52.0,44.0,0.004,NaN,강원 강릉시 옥천동,강원 강릉시,옥천동,632132,2016010103,2016,01,01,03
3,3,0.6,0.013,0.024,45.0,38.0,0.003,NaN,강원 강릉시 옥천동,강원 강릉시,옥천동,632132,2016010104,2016,01,01,04
4,4,0.6,0.013,0.025,43.0,37.0,0.004,NaN,강원 강릉시 옥천동,강원 강릉시,옥천동,632132,2016010105,2016,01,01,05

In [18]:
mise.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8990691 entries, 0 to 8990690
Data columns (total 18 columns):
Unnamed: 0    int64
CO            float64
NO2           float64
O3            float64
PM10          float64
PM25          float64
SO2           float64
망             object
주소            object
지역            object
측정소명          object
측정소코드         int64
측정일시          int64
연도            object
월             object
일             object
시간            object
시도            object
dtypes: float64(6), int64(3), object(9)
memory usage: 1.2+ GB

In [19]:
mise1 = mise[mise['시도'].values != '강원']
mise1 = mise1[mise1['시도'].values != '경기']
mise1 = mise1[mise1['시도'].values != '경남']
mise1 = mise1[mise1['시도'].values != '경북']
mise1 = mise1[mise1['시도'].values != '전북']
mise1 = mise1[mise1['시도'].values != '전남']
mise1 = mise1[mise1['시도'].values != '충남']
mise1 = mise1[mise1['시도'].values != '충북']
mise1 = mise1[mise1['시도'].values != '제주']
mise1 = mise1[mise1['시도'].values != '세종']

In [ ]:
mise1.info()

In [20]:
mise_fin = mise1[mise1['시간']=='11']

In [21]:
mise_fin=mise_fin.groupby(by=['시도','측정일시']).max()
mise_fin.reset_index(inplace=True)

In [ ]:
mise_fin.head()

In [ ]:
mise_fin.shape

In [22]:
mise_fin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7672 entries, 0 to 7671
Data columns (total 18 columns):
시도            7672 non-null object
측정일시          7672 non-null int64
Unnamed: 0    7672 non-null int64
CO            7672 non-null float64
NO2           7672 non-null float64
O3            7672 non-null float64
PM10          7672 non-null float64
PM25          7671 non-null float64
SO2           7672 non-null float64
망             1288 non-null object
주소            7672 non-null object
지역            7672 non-null object
측정소명          7672 non-null object
측정소코드         7672 non-null int64
연도            7672 non-null object
월             7672 non-null object
일             7672 non-null object
시간            7672 non-null object
dtypes: float64(6), int64(3), object(9)
memory usage: 1.1+ MB

In [23]:
mise_fin['시도'].value_counts()

인천    1096
대전    1096
울산    1096
광주    1096
대구    1096
부산    1096
서울    1096
Name: 시도, dtype: int64

In [24]:
mise_fin.loc[mise_fin['PM10']<=80,'PM10group'] = 0
mise_fin.loc[mise_fin['PM10']>80,'PM10group'] = 1
mise_fin.loc[mise_fin['PM10']>150,'PM10group'] = 2

In [25]:
mise_fin.loc[mise_fin['PM25']<=35,'PM25group'] = 0
mise_fin.loc[mise_fin['PM25']>35,'PM25group'] = 1
mise_fin.loc[mise_fin['PM25']>75,'PM25group'] = 2

In [26]:
mise_fin.head()

,시도,측정일시,Unnamed: 0,CO,NO2,O3,PM10,PM25,SO2,망,주소,지역,측정소명,측정소코드,연도,월,일,시간,PM10group,PM25group
0,광주,2016010111,307954,1.5,0.046,0.024,84.0,65.0,0.006,NaN,광주 서구 상무자유로 170,광주 서구,치평동,324155,2016,01,01,11,1.0,1.0
1,광주,2016010211,307978,1.5,0.058,0.030,83.0,54.0,0.005,NaN,광주 서구 상무자유로 170,광주 서구,치평동,324155,2016,01,02,11,1.0,1.0
2,광주,2016010311,308002,2.2,0.058,0.012,104.0,57.0,0.007,NaN,광주 서구 상무자유로 170,광주 서구,치평동,324155,2016,01,03,11,1.0,1.0
3,광주,2016010411,308026,1.1,0.036,0.046,168.0,127.0,0.008,NaN,광주 서구 상무자유로 170,광주 서구,치평동,324155,2016,01,04,11,2.0,2.0
4,광주,2016010511,308050,0.6,0.039,0.021,47.0,27.0,0.006,NaN,광주 서구 상무자유로 170,광주 서구,치평동,324155,2016,01,05,11,0.0,0.0

In [27]:
mise_fin['PM10group'].value_counts()

0.0    4908
1.0    2438
2.0     326
Name: PM10group, dtype: int64

In [60]:
mise_fin.head()

,시도,측정일시,Unnamed: 0,PM10,PM25,지역,연도,월,일,시간,PM10group,PM25group,날짜,요일,주말여부
0,광주,2016010111,307954,84.0,65.0,광주 서구,2016,01,01,11,1.0,1.0,20160101,3,평일
1,광주,2016010211,307978,83.0,54.0,광주 서구,2016,01,02,11,1.0,1.0,20160102,3,평일
2,광주,2016010311,308002,104.0,57.0,광주 서구,2016,01,03,11,1.0,1.0,20160103,3,평일
3,광주,2016010411,308026,168.0,127.0,광주 서구,2016,01,04,11,2.0,2.0,20160104,3,평일
4,광주,2016010511,308050,47.0,27.0,광주 서구,2016,01,05,11,0.0,0.0,20160105,3,평일

In [29]:
date = mise_fin['측정일시'].astype(str)
mise_fin['날짜'] = date.str.slice(start=0, stop=8).astype(str)

mise_fin['날짜2'] = pd.to_datetime(mise_fin['날짜'])

mise_fin['요일'] = mise_fin['날짜2'].dt.weekday

mise_fin['주말여부'] = np.where(mise_fin['요일']>=5, '주말','평일')

In [30]:
mise_fin

,시도,측정일시,Unnamed: 0,CO,NO2,O3,PM10,PM25,SO2,망,...,연도,월,일,시간,PM10group,PM25group,날짜,날짜2,요일,주말여부
0,광주,2016010111,307954,1.5,0.046,0.024,84.0,65.0,0.006,NaN,...,2016,01,01,11,1.0,1.0,20160101,2016-01-01,4,평일
1,광주,2016010211,307978,1.5,0.058,0.030,83.0,54.0,0.005,NaN,...,2016,01,02,11,1.0,1.0,20160102,2016-01-02,5,주말
2,광주,2016010311,308002,2.2,0.058,0.012,104.0,57.0,0.007,NaN,...,2016,01,03,11,1.0,1.0,20160103,2016-01-03,6,주말
3,광주,2016010411,308026,1.1,0.036,0.046,168.0,127.0,0.008,NaN,...,2016,01,04,11,2.0,2.0,20160104,2016-01-04,0,평일
4,광주,2016010511,308050,0.6,0.039,0.021,47.0,27.0,0.006,NaN,...,2016,01,05,11,0.0,0.0,20160105,2016-01-05,1,평일
5,광주,2016010611,308074,0.7,0.043,0.027,92.0,40.0,0.006,NaN,...,2016,01,06,11,1.0,1.0,20160106,2016-01-06,2,평일
6,광주,2016010711,308098,0.6,0.030,0.032,60.0,40.0,0.005,NaN,...,2016,01,07,11,0.0,1.0,20160107,2016-01-07,3,평일
7,광주,2016010811,308122,0.7,0.042,0.021,41.0,28.0,0.004,NaN,...,2016,01,08,11,0.0,0.0,20160108,2016-01-08,4,평일
8,광주,2016010911,308146,0.9,0.044,0.015,92.0,53.0,0.005,NaN,...,2016,01,09,11,1.0,1.0,20160109,2016-01-09,5,주말
9,광주,2016011011,308170,0.9,0.036,0.033,68.0,48.0,0.006,NaN,...,2016,01,10,11,0.0,1.0,20160110,2016-01-10,6,주말
10,광주,2016011111,308194,0.7,0.026,0.038,57.0,33.0,0.005,NaN,...,2016,01,11,11,0.0,0.0,20160111,2016-01-11,0,평일
11,광주,2016011211,308218,0.7,0.030,0.034,43.0,23.0,0.005,NaN,...,2016,01,12,11,0.0,0.0,20160112,2016-01-12,1,평일
12,광주,2016011311,308242,0.7,0.030,0.028,31.0,18.0,0.009,NaN,...,2016,01,13,11,0.0,0.0,20160113,2016-01-13,2,평일
13,광주,2016011411,308266,0.8,0.048,0.029,55.0,23.0,0.003,NaN,...,2016,01,14,11,0.0,0.0,20160114,2016-01-14,3,평일
14,광주,2016011511,308290,1.6,0.076,0.024,100.0,54.0,0.006,NaN,...,2016,01,15,11,1.0,1.0,20160115,2016-01-15,4,평일
15,광주,2016011611,308314,1.3,0.069,0.027,121.0,84.0,0.005,NaN,...,2016,01,16,11,1.0,2.0,20160116,2016-01-16,5,주말
16,광주,2016011711,308338,0.9,0.044,0.030,91.0,61.0,0.005,NaN,...,2016,01,17,11,1.0,1.0,20160117,2016-01-17,6,주말
17,광주,2016011811,308362,0.6,0.040,0.038,44.0,34.0,0.004,NaN,...,2016,01,18,11,0.0,0.0,20160118,2016-01-18,0,평일
18,광주,2016011911,308386,0.6,0.021,0.039,21.0,10.0,0.003,NaN,...,2016,01,19,11,0.0,0.0,20160119,2016-01-19,1,평일
19,광주,2016012011,308410,0.7,0.031,0.038,45.0,27.0,0.004,NaN,...,2016,01,20,11,0.0,0.0,20160120,2016-01-20,2,평일
20,광주,2016012111,308434,0.7,0.041,0.036,47.0,31.0,0.004,NaN,...,2016,01,21,11,0.0,0.0,20160121,2016-01-21,3,평일
21,광주,2016012211,308458,0.6,0.035,0.033,49.0,23.0,0.005,NaN,...,2016,01,22,11,0.0,0.0,20160122,2016-01-22,4,평일
22,광주,2016012311,308482,0.6,0.027,0.036,51.0,32.0,0.007,NaN,...,2016,01,23,11,0.0,0.0,20160123,2016-01-23,5,주말
23,광주,2016012411,308506,0.6,0.022,0.034,23.0,16.0,0.006,NaN,...,2016,01,24,11,0.0,0.0,20160124,2016-01-24,6,주말
24,광주,2016012511,308530,1.0,0.053,0.026,53.0,28.0,0.006,NaN,...,2016,01,25,11,0.0,0.0,20160125,2016-01-25,0,평일
25,광주,2016012611,308554,1.4,0.062,0.010,74.0,46.0,0.007,NaN,...,2016,01,26,11,0.0,1.0,20160126,2016-01-26,1,평일
26,광주,2016012711,308578,2.4,0.095,0.020,111.0,95.0,0.008,NaN,...,2016,01,27,11,1.0,2.0,20160127,2016-01-27,2,평일
27,광주,2016012811,308602,1.7,0.064,0.026,119.0,82.0,0.007,NaN,...,2016,01,28,11,1.0,2.0,20160128,2016-01-28,3,평일
28,광주,2016012911,308626,1.3,0.062,0.016,73.0,50.0,0.005,NaN,...,2016,01,29,11,0.0,1.0,20160129,2016-01-29,4,평일
29,광주,2016013011,308650,0.9,0.049,0.024,65.0,48.0,0.005,NaN,...,2016,01,30,11,0.0,1.0,20160130,2016-01-30,5,주말
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7642,인천,2018120211,8989981,1.0,0.059,0.028,98.0,51.0,0.012,도시대기,...,2018,12,02,11,1.0,1.0,20181202,2018-12-02,6,주말
7643,인천,2018120311,8990005,1.0,0.055,0.029,76.0,31.0,0.007,도시대기,...,2018,12,03,11,0.0,0.0,20181203,2018-12-03,0,평일
7644,인천,2018120411,8990029,0.9,0.042,0.031,76.0,22.0,0.006,도시대기,...,2018,12,04,11,0.0,0.0,20181204,2018-12-04,1,평일
7645,인천,2018120511,8990053,0.8,0.039,0.033,72.0,17.0,0.007,도시대기,...,2018,12,05,11,0.0,0.0,20181205,2018-12-05,2,평일
7646,인천,2018120611,8990077,0.7,0.050,0.033,91.0,33.0,0.008,도시대기,...,2018,12,06,11,1.0,0.0,20181206,2018-12-06,3,평일
7647,인천,2018120711,8990101,0.7,0.033,0.034,51.0,19.0,0.006,도시대기,...,2018,12,07,11,0.0,0.0,20181207,2018-12-07,4,평일
7648,인천,2018120811,8990125,0.8,0.022,0.032,50.0,18.0,0.006,도시대기,...,2018,12,08,11,0.0,0.0,20181208,2018-12-08,5,주말
7649,인천,2018120911,8990149,0.9,0.029,0.038,43.0,23.0,0.008,도시대기,...,2018,12,09,11,0.0,0.0,20181209,2018-12-09,6,주말
7650,인천,2018121011,8990173,1.3,0.079,0.035,83.0,40.0,0.010,도시대기,...,2018,12,10,11,1.0,1.0,20181210,2018-12-10,0,평일
7651,인천,2018121111,8990197,1.0,0.069,0.037,105.0,40.0,0.008,도시대기,...,2018,12,11,11,1.0,1.0,20181211,2018-12-11,1,평일
7652,인천,2018121211,8990221,0.7,0.036,0.038,75.0,29.0,0.007,도시대기,...,2018,12,12,11,0.0,0.0,20181212,2018-12-12,2,평일
7653,인천,2018121311,8990245,1.1,0.066,0.032,72.0,51.0,0.008,도시대기,...,2018,12,13,11,0.0,1.0,20181213,2018-12-13,3,평일
7654,인천,2018121411,8990269,0.7,0.038,0.038,62.0,38.0,0.007,도시대기,...,2018,12,14,11,0.0,1.0,20181214,2018-12-14,4,평일
7655,인천,2018121511,8990293,1.4,0.093,0.037,119.0,62.0,0.008,도시대기,...,2018,12,15,11,1.0,1.0,20181215,2018-12-15,5,주말
7656,인천,2018121611,8990317,0.9,0.063,0.037,76.0,54.0,0.008,도시대기,...,2018,12,16,11,0.0,1.0,20181216,2018-12-16,6,주말
7657,인천,2018121711,8990341,1.2,0.055,0.037,138.0,94.0,0.013,도시대기,...,2018,12,17,11,1.0,2.0,20181217,2018-12-17,0,평일
7658,인천,2018121811,8990365,1.3,0.097,0.037,103.0,64.0,0.014,도시대기,...,2018,12,18,11,1.0,1.0,20181218,2018-12-18,1,평일
7659,인천,2018121911,8990389,1.4,0.063,0.031,108.0,71.0,0.012,도시대기,...,2018,12,19,11,1.0,1.0,20181219,2018-12-19,2,평일
7660,인천,2018122011,8990413,1.6,0.099,0.034,132.0,75.0,0.013,도시대기,...,2018,12,20,11,1.0,1.0,20181220,2018-12-20,3,평일
7661,인천,2018122111,8990437,1.5,0.092,0.028,131.0,66.0,0.018,도시대기,...,2018,12,21,11,1.0,1.0,20181221,2018-12-21,4,평일
7662,인천,2018122211,8990461,1.1,0.061,0.042,115.0,78.0,0.015,도시대기,...,2018,12,22,11,1.0,2.0,20181222,2018-12-22,5,주말
7663,인천,2018122311,8990485,0.8,0.031,0.042,66.0,30.0,0.009,도시대기,...,2018,12,23,11,0.0,0.0,20181223,2018-12-23,6,주말
7664,인천,2018122411,8990509,0.7,0.051,0.040,48.0,24.0,0.009,도시대기,...,2018,12,24,11,0.0,0.0,20181224,2018-12-24,0,평일
7665,인천,2018122511,8990533,0.9,0.062,0.035,63.0,36.0,0.008,도시대기,...,2018,12,25,11,0.0,1.0,20181225,2018-12-25,1,평일
7666,인천,2018122611,8990557,0.7,0.046,0.040,78.0,47.0,0.009,도시대기,...,2018,12,26,11,0.0,1.0,20181226,2018-12-26,2,평일
7667,인천,2018122711,8990581,0.5,0.024,0.039,53.0,17.0,0.006,도시대기,...,2018,12,27,11,0.0,0.0,20181227,2018-12-27,3,평일
7668,인천,2018122811,8990605,0.7,0.034,0.035,58.0,23.0,0.006,도시대기,...,2018,12,28,11,0.0,0.0,20181228,2018-12-28,4,평일
7669,인천,2018122911,8990629,0.5,0.029,0.039,69.0,18.0,0.007,도시대기,...,2018,12,29,11,0.0,0.0,20181229,2018-12-29,5,주말
7670,인천,2018123011,8990653,0.9,0.025,0.039,42.0,20.0,0.009,도시대기,...,2018,12,30,11,0.0,0.0,20181230,2018-12-30,6,주말
7671,인천,2018123111,8990677,1.5,0.078,0.042,118.0,58.0,0.013,도시대기,...,2018,12,31,11,1.0,1.0,20181231,2018-12-31,0,평일

In [31]:
mise10 = pd.crosstab([mise_fin['시도'],mise_fin['연도'],mise_fin['주말여부']],mise_fin['PM10group'],normalize='index')

mise25 = pd.crosstab([mise_fin['시도'],mise_fin['연도'],mise_fin['주말여부']],mise_fin['PM25group'],normalize='index')

In [32]:
mise10.to_csv('mise10.csv',encoding='ms949')

In [33]:
mise25.to_csv('mise25.csv',encoding='ms949')

In [41]:
mise10

PM10group          0.0       1.0       2.0
시도 연도   주말여부
광주 2016 주말    0.733333  0.209524  0.057143
        평일    0.758621  0.226054  0.015326
   2017 주말    0.790476  0.190476  0.019048
        평일    0.765385  0.219231  0.015385
   2018 주말    0.788462  0.192308  0.019231
        평일    0.770115  0.206897  0.022989
대구 2016 주말    0.542857  0.380952  0.076190
        평일    0.628352  0.298851  0.072797
   2017 주말    0.723810  0.219048  0.057143
        평일    0.673077  0.288462  0.038462
   2018 주말    0.721154  0.240385  0.038462
        평일    0.681992  0.260536  0.057471
대전 2016 주말    0.723810  0.219048  0.057143
        평일    0.727969  0.260536  0.011494
   2017 주말    0.676190  0.285714  0.038095
        평일    0.700000  0.280769  0.019231
   2018 주말    0.663462  0.288462  0.048077
        평일    0.693487  0.272031  0.034483
부산 2016 주말    0.609524  0.304762  0.085714
        평일    0.551724  0.394636  0.053640
   2017 주말    0.628571  0.323810  0.047619
        평일    0.569231  0.400000  0.030769
   2018 주말    0.721154  0.250000  0.028846
        평일    0.632184  0.321839  0.045977
서울 2016 주말    0.485714  0.438095  0.076190
        평일    0.375479  0.551724  0.072797
   2017 주말    0.485714  0.428571  0.085714
        평일    0.426923  0.515385  0.057692
   2018 주말    0.644231  0.326923  0.028846
        평일    0.659004  0.321839  0.019157
울산 2016 주말    0.666667  0.276190  0.057143
        평일    0.674330  0.295019  0.030651
   2017 주말    0.704762  0.257143  0.038095
        평일    0.603846  0.361538  0.034615
   2018 주말    0.750000  0.201923  0.048077
        평일    0.674330  0.287356  0.038314
인천 2016 주말    0.495238  0.438095  0.066667
        평일    0.478927  0.482759  0.038314
   2017 주말    0.590476  0.342857  0.066667
        평일    0.569231  0.365385  0.065385
   2018 주말    0.663462  0.288462  0.048077
        평일    0.670498  0.291188  0.038314

In [79]:
mise25

PM25group          0.0       1.0       2.0
시도 연도   주말여부
광주 2016 주말    0.523810  0.438095  0.038095
        평일    0.582375  0.375479  0.042146
   2017 주말    0.542857  0.419048  0.038095
        평일    0.569231  0.380769  0.050000
   2018 주말    0.625000  0.317308  0.057692
        평일    0.609195  0.337165  0.053640
대구 2016 주말    0.409524  0.466667  0.123810
        평일    0.463602  0.409962  0.126437
   2017 주말    0.523810  0.371429  0.104762
        평일    0.469231  0.376923  0.153846
   2018 주말    0.548077  0.384615  0.067308
        평일    0.517241  0.356322  0.126437
대전 2016 주말    0.600000  0.390476  0.009524
        평일    0.684615  0.300000  0.015385
   2017 주말    0.619048  0.314286  0.066667
        평일    0.626923  0.330769  0.042308
   2018 주말    0.596154  0.346154  0.057692
        평일    0.624521  0.321839  0.053640
부산 2016 주말    0.419048  0.495238  0.085714
        평일    0.344828  0.547893  0.107280
   2017 주말    0.495238  0.447619  0.057143
        평일    0.403846  0.530769  0.065385
   2018 주말    0.548077  0.394231  0.057692
        평일    0.498084  0.425287  0.076628
서울 2016 주말    0.466667  0.495238  0.038095
        평일    0.540230  0.436782  0.022989
   2017 주말    0.552381  0.371429  0.076190
        평일    0.615385  0.330769  0.053846
   2018 주말    0.500000  0.413462  0.086538
        평일    0.551724  0.375479  0.072797
울산 2016 주말    0.504762  0.447619  0.047619
        평일    0.636015  0.321839  0.042146
   2017 주말    0.619048  0.333333  0.047619
        평일    0.576923  0.369231  0.053846
   2018 주말    0.586538  0.355769  0.057692
        평일    0.547893  0.348659  0.103448
인천 2016 주말    0.323810  0.542857  0.133333
        평일    0.383142  0.521073  0.095785
   2017 주말    0.447619  0.409524  0.142857
        평일    0.434615  0.453846  0.111538
   2018 주말    0.557692  0.346154  0.096154
        평일    0.555556  0.352490  0.091954

In [35]:
mise_subset = mise_fin[['시도','연도','PM10','PM25','SO2','CO','O3','NO2']]

In [40]:
mise_subset.head()

   시도    연도   PM10   PM25    SO2   CO     O3    NO2
0  광주  2016   84.0   65.0  0.006  1.5  0.024  0.046
1  광주  2016   83.0   54.0  0.005  1.5  0.030  0.058
2  광주  2016  104.0   57.0  0.007  2.2  0.012  0.058
3  광주  2016  168.0  127.0  0.008  1.1  0.046  0.036
4  광주  2016   47.0   27.0  0.006  0.6  0.021  0.039

In [39]:
mise_fin.to_csv('미세상관계수.csv',encoding='ms949')

In [42]:
save = mise_fin.groupby(['시도','연도']).corr()

In [43]:
save.to_csv('misecorr.csv',encoding='ms949')